[package]
name = "sudachi_swift"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Swift bindings of sudachi.rs, the Japanese Morphological Analyzer"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "lib"]
name = "sudachi_swift"

[dependencies]
sudachi = { path = "../sudachi" }
uniffi = { version = "0.31.0", default-features = false }
thiserror = "2.0.18"
